# Generated by Django 3.0.5 on 2020-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('open_from', models.TimeField()),
                ('open_until', models.TimeField()),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('default_backdrop', models.FileField(blank=True, null=True, upload_to='vendor_backdrops/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('unit_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3)),
                ('unit_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=5)),
                ('num_left', models.PositiveSmallIntegerField()),
                ('collect_from', models.TimeField()),
                ('collect_until', models.TimeField()),
                ('backdrop', models.FileField(blank=True, null=True, upload_to='offer_backdrops/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.Vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
