# Generated by Django 3.0.5 on 2020-05-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'paid'), (1, 'collected')], default=0)),
                ('collected_at', models.DateTimeField(blank=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
